project:
  type: website

website:
  title: "filipwastberg"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/filipwastberg
      - icon: twitter
        href: https://twitter.com/filipwastberrrg
format:
  html:
    theme: literal
    css: styles.css
execute:
  freeze: auto



